group_dict = {
    "hljp0": ['azi', 'miko', 'roboco', 'sora', 'suisei'],
    "hljp1": ['mel', 'haato', 'fubuki', 'matsuri', 'aki'],
    "hljp2": ['shion', 'aqua', 'ayame', 'choco', 'choco_sub', 'subaru'],
    "hljp_g": ['korone', 'mio', 'okayu'],
    "hljp3": ['noel', 'rushia', 'pekora', 'flare', 'marine'],
    "hljp4": ['luna', 'coco', 'watame', 'kanata', 'towa'],
    "hljp5": ['lamy', 'nene', 'botan', 'polka'],
    "hlen1": ['calli', 'kiara', 'ina', 'gura', 'amelia'],
    "hlid1": ['risu', 'moona', 'iofi'],
    "hlid2": ['reine', 'anya', 'ollie'],
    "hstars1": ['miyabi', 'kira', 'izuru', 'aruran', 'rikka'],
    "hstars2": ['astel', 'temma', 'roberu'],
    "hstars3": ['shien', 'oga'],
    "voms": ['pikamee', 'tomoshika'],
    "niji": ['lulu', 'hana'],
    "ind": ['uto']
}

hljp = group_dict['hljp0'] + group_dict['hljp1'] + group_dict['hljp2'] + group_dict['hljp_g'] + group_dict['hljp3'] + group_dict['hljp4'] + group_dict['hljp5']
hlen = group_dict['hlen1']
hlid = group_dict['hlid1'] + group_dict['hlid2']
hstars = group_dict['hstars1'] + group_dict['hstars2'] + group_dict['hstars3']

# master playlist ids go here (replace the UC in the channel id to UU)
channel_ids = {
    "azki": "UU0TXe_LYZ4scaW2XMyi5_kw",
    "miko": "UU-hM6YJuNYVAmUWxeIr9FeA",
    "roboco": "UUDqI2jOz0weumE8s7paEk6g", 
    "sora": "UUp6993wxpyDPHUpavwDFqgg",
    "suisei": "UU5CwaMl1eIgY8h02uZw7u8A",
    "mel": "UUD8HOxPs4Xvsm8H0ZxXGiBw",
    "haato": "UU1CfXB_kRs3C-zaeTG3oGyg",
    "fubuki": "UUdn5BQ06XqgXoAxIhbqw5Rg",
    "matsuri": "UUQ0UDLQCjY0rmuxCDE38FGg",
    "aki": "UUFTLzh12_nrtzqBPsTCqenA",
    "shion": "UUXTpFs_3PqI41qX2d9tL2Rw",
    "aqua": "UU1opHUrw8rvnsadT-iGp7Cg",
    "ayame": "UU7fk0CB07ly8oSl0aqKkqFg",
    "choco": "UU1suqwovbL1kzsoaZgFZLKg",
    "choco_sub": "UUp3tgHXw_HI0QMk1K8qh3gQ",
    "subaru": "UUvzGlP9oQwU--Y0r9id_jnA",
    "korone": "UUhAnqc_AY5_I3Px5dig3X1Q",
    "mio": "UUp-5t9SrOQwXMU7iIjQfARg",
    "okayu": "UUvaTdHTWBGv3MKj3KVqJVCw",
    "noel": "UUdyqAaZDKHXg4Ahi7VENThQ",
    "rushia": "UUl_gCybOJRIgOXw6Qb4qJzQ",
    "pekora": "UU1DCedRgGHBdm81E1llLhOQ",
    "flare": "UUvInZx9h3jC2JzsIzoOebWg",
    "marine": "UUCzUftO8KOVkV4wQG1vkUvg",
    "luna": "UUa9Y57gfeY0Zro_noHRVrnw",
    "coco": "UUS9uQI-jC3DE0L4IpXyvr6w",
    "watame": "UUqm3BQLlJfvkTsX_hvm0UmA",
    "kanata": "UUZlDXzGoo7d44bwdNObFacg",
    "towa": "UU1uv2Oq6kNxgATlCiez59hw",
    "lamy": "UUFKOVgVbGmX65RxO3EtH3iw",
    "nene": "UUAWSyEs_Io8MtpY3m-zqILA",
    "botan": "UUUKD-uaobj9jiqB-VXt71mA",
    "polka": "UUK9V2B22uJYu3N7eR_BT9QA",
    "calli": "UUL_qhgtOy0dy1Agp8vkySQg",
    "kiara": "UUHsx4Hqa-1ORjQTh9TYDhww",
    "ina": "UUMwGHR0BTZuLsmjY_NT5Pwg",
    "gura": "UUoSrY_IQQVpmIRZ9Xf-y93g",
    "amelia": "UUyl1z3jo3XHR1riLFKG5UAg",
    "risu": "UUOyYb1c43VlX9rc_lT6NKQw",
    "moona": "UUP0BspO_AMEe3aQqqpo89Dg",
    "iofi": "UUAoy6rzhSf4ydcYjJw3WoVg",
    "reine": "UUhgTyjG-pdNvxxhdsXfHQ5Q",
    "anya": "UU727SQYUvx5pDDGQpTICNWg",
    "ollie": "UUYz_5n-uDuChHtLo7My1HnQ",
    "miyabi": "UU6t3-_N8A6ME1JShZHHqOMw",
    "kira": "UUEzsociuFqVwgZuMaZqaCsg",
    "izuru": "UUZgOv3YDEs-ZnZWDYVwJdmA",
    "aruran": "UUKeAhJvy8zgXWbh9duVjIaQ",
    "rikka": "UU9mf_ZVpouoILRY9NUIaK-w",
    "astel": "UUNVEsYbiZjH5QLmGeSgTSzg",
    "temma": "UUGNI4MENvnsymYjKiZwv9eg",
    "roberu": "UUANDOlYTJT7N5jlRC3zfzVA",
    "shien": "UUhSvpZYRPh0FvG4SJGSga3g",
    "oga": "UUwL7dgTxKo8Y4RFIKWaf8gA",
    "hololive_ch": "UUJFZiqLMntJufDCHc6bQixg",
    "holostars_ch": "UUWsfcksUUpoEvhia0_ut0bA",
    "pikamee": "UUajhBT4nMrg3DLS-bLL2RCg",
    "tomoshika": "UU3vzVK_N_SUVKqbX69L_X4g",
    "lulu": "UU_a1ZYZ8ZTXpjg9xUY9sj8w",
    "hana": "UUpJtk0myFr5WnyfsmnInP-w",
    "uto": "UUdYR5Oyz8Q4g0ZmB4PkTD7g"
 }