group_dict = {
    "hljp0": ['azki', 'miko', 'roboco', 'sora', 'suisei'],
    "hljp1": ['mel', 'haato', 'fubuki', 'matsuri', 'aki'],
    "hljp2": ['shion', 'aqua', 'ayame', 'choco', 'choco_sub', 'subaru'],
    "hljp_g": ['korone', 'mio', 'okayu'],
    "hljp3": ['noel', 'pekora', 'flare', 'marine'],
    "hljp4": ['luna', 'watame', 'kanata', 'towa'],
    "hljp5": ['lamy', 'nene', 'botan', 'polka'],
    "hljp6": ['laplus', 'lui', 'koyori', 'chloe', 'iroha'],
    "hlen1": ['calli', 'kiara', 'ina', 'gura', 'amelia', 'irys', 'kiara_sub'],
    "hlid1": ['risu', 'moona', 'iofi'],
    "hlid2": ['reine', 'anya', 'ollie'],
    "hlid3": ['zeta', 'kaela', 'kobo'],
	"regloss1": ['hajime', 'raden', 'ao', 'ririka', 'kanade'],
    "hlall": ['azki', 'miko', 'roboco', 'sora', 'suisei', 'haato', 'fubuki', 'matsuri', 'aki', 'shion', 'aqua', 'ayame', 'choco', 'choco_sub', 'subaru', 'korone', 'mio', 'okayu', 'noel', 'pekora', 'flare', 'marine', 'luna', 'watame', 'kanata', 'towa', 'lamy', 'nene', 'botan', 'polka', 'laplus', 'lui', 'koyori', 'chloe', 'iroha', 'calli', 'kiara', 'kiara_sub', 'ina', 'gura', 'amelia', 'irys', 'fauna', 'kronii', 'mumei', 'baelz', 'shiori', 'bijou', 'nerissa', 'fuwamoco', 'risu', 'moona', 'iofi', 'reine', 'anya', 'ollie', 'zeta', 'kaela', 'kobo', 'hajime', 'raden', 'ao', 'ririka', 'kanade']
}

hljp = group_dict['hljp0'] + group_dict['hljp1'] + group_dict['hljp2'] + group_dict['hljp_g'] + group_dict['hljp3'] + group_dict['hljp4'] + group_dict['hljp5'] + group_dict['hljp6']
hlen = group_dict['hlen1']
hlid = group_dict['hlid1'] + group_dict['hlid2'] + group_dict['hlid3']

# master playlist ids go here (replace the UC in the channel id to UU)
channel_ids = {
    "azki": "UU0TXe_LYZ4scaW2XMyi5_kw",
    "miko": "UU-hM6YJuNYVAmUWxeIr9FeA",
    "roboco": "UUDqI2jOz0weumE8s7paEk6g", 
    "sora": "UUp6993wxpyDPHUpavwDFqgg",
    "suisei": "UU5CwaMl1eIgY8h02uZw7u8A",
    "haato": "UU1CfXB_kRs3C-zaeTG3oGyg",
    "fubuki": "UUdn5BQ06XqgXoAxIhbqw5Rg",
    "matsuri": "UUQ0UDLQCjY0rmuxCDE38FGg",
    "aki": "UUFTLzh12_nrtzqBPsTCqenA",
    "shion": "UUXTpFs_3PqI41qX2d9tL2Rw",
    "aqua": "UU1opHUrw8rvnsadT-iGp7Cg",
    "ayame": "UU7fk0CB07ly8oSl0aqKkqFg",
    "choco": "UU1suqwovbL1kzsoaZgFZLKg",
    "choco_sub": "UUp3tgHXw_HI0QMk1K8qh3gQ",
    "subaru": "UUvzGlP9oQwU--Y0r9id_jnA",
    "korone": "UUhAnqc_AY5_I3Px5dig3X1Q",
    "mio": "UUp-5t9SrOQwXMU7iIjQfARg",
    "okayu": "UUvaTdHTWBGv3MKj3KVqJVCw",
    "noel": "UUdyqAaZDKHXg4Ahi7VENThQ",
    "pekora": "UU1DCedRgGHBdm81E1llLhOQ",
    "flare": "UUvInZx9h3jC2JzsIzoOebWg",
    "marine": "UUCzUftO8KOVkV4wQG1vkUvg",
    "luna": "UUa9Y57gfeY0Zro_noHRVrnw",
    #"coco": "UUS9uQI-jC3DE0L4IpXyvr6w",
    "watame": "UUqm3BQLlJfvkTsX_hvm0UmA",
    "kanata": "UUZlDXzGoo7d44bwdNObFacg",
    "towa": "UU1uv2Oq6kNxgATlCiez59hw",
    "lamy": "UUFKOVgVbGmX65RxO3EtH3iw",
    "nene": "UUAWSyEs_Io8MtpY3m-zqILA",
    "botan": "UUUKD-uaobj9jiqB-VXt71mA",
    "polka": "UUK9V2B22uJYu3N7eR_BT9QA",
    "laplus": "UUENwRMx5Yh42zWpzURebzTw",
    "lui": "UUs9_O1tRPMQTHQ-N_L6FU2g",
    "koyori": "UU6eWCld0KwmyHFbAqK3V-Rw",
    "chloe": "UUIBY1ollUsauvVi4hW4cumw",
    "iroha": "UU_vMYWcDjmfdpH6r4TTn1MQ",
    "calli": "UUL_qhgtOy0dy1Agp8vkySQg",
    "kiara": "UUHsx4Hqa-1ORjQTh9TYDhww",
    "kiara_sub": "UUq4ky2drohLT7W0DmDEw1dQ",
    "ina": "UUMwGHR0BTZuLsmjY_NT5Pwg",
    "gura": "UUoSrY_IQQVpmIRZ9Xf-y93g",
    "amelia": "UUyl1z3jo3XHR1riLFKG5UAg",
    "irys": "UU8rcEBzJSleTkf_-agPM20g",
    #"sana": 'UUsUj0dszADCGbF3gNrQEuSQ',
    "fauna": 'UUO_aKKYxn4tvrqPjcTzZ6EQ',
    "kronii": 'UUmbs8T6MWqUHP1tIQvSgKrg',
    "mumei": 'UU3n5uGu18FoCy23ggWWp8tA',
    "baelz": 'UUgmPnx-EEeOrZSg5Tiw7ZRQ',
	"shiori": 'UUgnfPPb9JI3e9A4cXHnWbyg',
	"bijou": 'UU9p_lqQ0FEDz327Vgf5JwqA',
	"nerissa": 'UU_sFNM0z0MWm9A6WlKPuMMg',
	"fuwamoco": 'UUt9H_RpQzhxzlyBxFqrdHqA',
    "risu": "UUOyYb1c43VlX9rc_lT6NKQw",
    "moona": "UUP0BspO_AMEe3aQqqpo89Dg",
    "iofi": "UUAoy6rzhSf4ydcYjJw3WoVg",
    "reine": "UUhgTyjG-pdNvxxhdsXfHQ5Q",
    "anya": "UU727SQYUvx5pDDGQpTICNWg",
    "ollie": "UUYz_5n-uDuChHtLo7My1HnQ",
    "zeta": "UUTvHWSfBZgtxE4sILOaurIQ",
    "kaela": "UUZLZ8Jjx_RN2CXloOmgTHVg",
    "kobo": "UUjLEmnpCNeisMxy134KPwWw",
    "hajime": "UU1iA6_NT4mtAcIII6ygrvCw",
	"raden": "UUdXAk5MpyLD8594lm_OvtGQ",
	"ao": "UUMGfV7TVTmHhEErVJg1oHBQ",
	"ririka": "UUtyWhCj3AqKh2dXctLkDtng",
	"kanade": "UUWQtYtq9EOB4-I5P-3fh8lA"
 }